import os
import time
import requests
from typing import Dict, Optional, List
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ.get("WLT_API_KEY", "YOUR_API_KEY_HERE")
BASE_URL = "https://api.worldlabs.ai/marble/v1"
HEADERS = {
    "Content-Type": "application/json",
    "WLT-Api-Key": API_KEY
}

MODEL = "marble-1.1-plus"

# Master campus panorama — generated by campus_master.py.
# Used as image input to anchor spatial consistency across all scenes.
MASTER_PANO_URL = os.environ.get("MASTER_PANO_URL")

# ---------------------------------------------------------------------------
# SCENE 1 — "THE TREE"
#
# Directorial intent:
#   Opens with the ENTIRE campus — the full world the story takes place in.
#   The tree is the undeniable center of that world. We reveal beauty at
#   every scale: campus → courtyard → trunk → canopy → roots.
#   No students yet. The audience falls in love with what they cannot see.
#
# Shot order: wide → closer → closer → detail → back to wide with contrast.
# Reference: the monolith reveal, 2001: A Space Odyssey.
# ---------------------------------------------------------------------------

SHOTS: List[Dict] = [
    {
        "id": "1A",
        "label": "Full Campus — The World Revealed",
        "display_name": "Tree_S01_1A_Campus",
        "prompt": (
            "Sweeping aerial wide shot revealing the entire university campus in full summer. "
            "The campus fills the frame — Gothic and modernist stone buildings, ivy-covered walls, "
            "cobblestone courtyards, winding pathways, an open green recreational field. "
            "At the absolute center of it all: a single colossal ancient oak tree, its lush deep green "
            "summer canopy towering above everything, unmistakably the heart of this world. "
            "The campus is breathtaking, alive, sun-drenched. No people visible. "
            "70mm film look, epic god's-eye establishing shot, hyper-realistic, cinematic, "
            "lush green summer palette, awe-inspiring scale."
        ),
        "use_master": True,
    },
    {
        "id": "1B",
        "label": "Courtyard Wide — Tree as Centerpiece",
        "display_name": "Tree_S01_1B_Courtyard",
        "prompt": (
            "Wide ground-level shot of the central university courtyard. "
            "The massive ancient oak tree dominates the center — its enormous trunk, vast spreading "
            "canopy of lush deep green summer leaves dwarfing the surrounding stone university buildings. "
            "Long dramatic shadows stretch across the cobblestone courtyard. "
            "The tree radiates quiet, undeniable presence. No people. "
            "70mm film look, anamorphic lens flare, hyper-realistic, cinematic, summer morning light."
        ),
        "use_master": True,
    },
    {
        "id": "1C",
        "label": "Worm's Eye — Monolith Reveal",
        "display_name": "Tree_S01_1C_Monolith",
        "prompt": (
            "Extreme low angle worm's-eye view looking straight up the trunk of a massive ancient oak tree, "
            "rugged deeply furrowed bark filling the entire frame, the trunk rising impossibly tall like a "
            "cathedral column, branches reaching outward like arms against a deep blue summer sky. "
            "The tree feels monolithic, towering, divine — a silent sentinel. "
            "Bright summer light catches the bark texture. No humans. "
            "70mm film look, high contrast, cinematic lighting, hyper-realistic, awe-inspiring."
        ),
        "use_master": True,
    },
    {
        "id": "1D",
        "label": "Canopy Upshot — Natural Cathedral",
        "display_name": "Tree_S01_1D_Canopy",
        "prompt": (
            "Looking up through the vast canopy of an ancient oak tree in full summer leaf. "
            "Thousands of lush deep green leaves filter brilliant sunlight into scattered rays and soft bokeh. "
            "The canopy forms a natural cathedral ceiling — transcendent, sacred, breathtaking. "
            "Patches of deep blue summer sky visible between the leaves. "
            "Light is bright, vibrant, alive with green glow. No people. "
            "70mm film look, shallow depth of field, hyper-realistic, cinematic."
        ),
        "use_master": True,
    },
    {
        "id": "1E",
        "label": "Root Level — Nature vs Stone",
        "display_name": "Tree_S01_1E_Roots",
        "prompt": (
            "Ground-level shot showing the massive gnarled roots of an ancient oak tree spreading "
            "organically across old cobblestones, cracking and lifting the pavement — "
            "nature quietly reclaiming the campus. The trunk rises powerfully above. "
            "Behind it: warm stone university buildings, ivy-covered walls, arched windows. "
            "Summer morning, peaceful, timeless. No people. "
            "70mm film look, warm morning light, cinematic, contemplative, hyper-realistic."
        ),
        "use_master": True,
    },
    {
        "id": "1F",
        "label": "Transition — Campus Full, Students Oblivious",
        "display_name": "Tree_S01_1F_Oblivious",
        "prompt": (
            "Wide shot pulling back to reveal the full beautiful university campus courtyard. "
            "The majestic ancient oak tree stands glorious and enormous at the center, "
            "its canopy full and richly green in bright summer light. "
            "Streams of university students flow past on the cobblestone paths in every direction — "
            "every single one with their head bowed down, face illuminated by the glow of a smartphone. "
            "The campus and the tree are magnificent; the students are blind to all of it. "
            "70mm film look, cinematic wide, bright summer morning, hyper-realistic, "
            "melancholy and ironic — beauty ignored."
        ),
        "use_master": True,
    },
]


def build_payload(shot: Dict) -> Dict:
    """Build generation payload, using master panorama as image anchor if available."""
    if shot.get("use_master") and MASTER_PANO_URL:
        return {
            "display_name": shot["display_name"],
            "model": MODEL,
            "world_prompt": {
                "type": "image",
                "image_prompt": {
                    "source": "uri",
                    "uri": MASTER_PANO_URL,
                    "is_pano": True,
                },
                "text_prompt": shot["prompt"],
            },
        }
    else:
        return {
            "display_name": shot["display_name"],
            "model": MODEL,
            "world_prompt": {
                "type": "text",
                "text_prompt": shot["prompt"],
            },
        }


def create_world(shot: Dict) -> Optional[str]:
    print(f"\n{'='*60}")
    print(f"  Shot {shot['id']} — {shot['label']}")
    print(f"{'='*60}")
    anchored = shot.get("use_master") and MASTER_PANO_URL
    print(f"  Mode:  {'image (anchored to master)' if anchored else 'text only (no master pano set)'}")
    print("  Initiating generation...")

    response = requests.post(
        f"{BASE_URL}/worlds:generate",
        headers=HEADERS,
        json=build_payload(shot)
    )

    if response.status_code in {200, 201, 202}:
        operation_id = response.json().get("operation_id")
        print(f"  Started. Operation ID: {operation_id}")
        return operation_id
    else:
        print(f"  ERROR {response.status_code}: {response.text}")
        return None


def poll_for_completion(operation_id: str, shot_id: str, poll_interval: int = 15) -> Dict:
    print(f"  Polling [{shot_id}] ", end="", flush=True)
    world_id = None

    while True:
        response = requests.get(f"{BASE_URL}/operations/{operation_id}", headers=HEADERS)
        data = response.json()

        metadata = data.get("metadata") or {}
        progress = metadata.get("progress") or {}
        status = progress.get("status", "")

        if not world_id and metadata.get("world_id"):
            world_id = metadata["world_id"]
            print(f"\n  World ID (mid-gen): {world_id}")
            print(f"  Preview: https://marble.worldlabs.ai/world/{world_id}")
            print(f"  Status  ", end="", flush=True)

        if data.get("done"):
            if data.get("error"):
                raise Exception(f"Generation failed: {data['error']}")
            print(f" {status}")
            return data.get("response", {})

        print(".", end="", flush=True)
        time.sleep(poll_interval)


def get_full_world(world_id: str) -> Dict:
    response = requests.get(f"{BASE_URL}/worlds/{world_id}", headers=HEADERS)
    return response.json().get("world", {})


def print_assets(shot: Dict, world: Dict) -> None:
    assets = world.get("assets", {})
    spz_urls = assets.get("splats", {}).get("spz_urls", {})
    print(f"\n  Assets for Shot {shot['id']} — {shot['label']}:")
    print(f"    Web Viewer:       {world.get('world_marble_url')}")
    print(f"    Collision (.glb): {assets.get('mesh', {}).get('collider_mesh_url')}")
    print(f"    Thumbnail:        {assets.get('thumbnail_url')}")
    print(f"    Splat full_res:   {spz_urls.get('full_res')}")
    print(f"    Splat 500k:       {spz_urls.get('500k')}")
    print(f"    Splat 100k:       {spz_urls.get('100k')}")
    print(f"    Panorama (.jpg):  {assets.get('imagery', {}).get('pano_url')}")
    print(f"    Caption:          {(assets.get('caption') or '')[:120]}")
    print(f"    World ID:         {world.get('id')}")


if __name__ == "__main__":
    if API_KEY == "YOUR_API_KEY_HERE":
        print("Please set WLT_API_KEY in your .env file.")
    else:
        if not MASTER_PANO_URL:
            print("WARNING: MASTER_PANO_URL not set in .env — running in text-only mode.")
            print("Run campus_master.py first for spatially consistent results.\n")

        print("\nTREE — Scene 01: 'The Tree'")
        print(f"Model: {MODEL} | Shots: {len(SHOTS)}\n")

        for shot in SHOTS:
            operation_id = create_world(shot)
            if operation_id:
                snapshot = poll_for_completion(operation_id, shot["id"])
                world_id = snapshot.get("id")
                world = get_full_world(world_id) if world_id else snapshot
                print_assets(shot, world)

        print("\n\nScene 01 complete.")
