using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// StoryboardCamera — TREE Scene 01, Gaussian Splat viewer.
///
/// SETUP
/// ─────
/// 1. In Edit mode, orbit until you see the courtyard + tree roughly centred
///    (shot 1B composition). Leave the camera there.
/// 2. Press Play. The script snapshots that Edit-mode pose as the calibration
///    baseline. Shot 1B loads with zero offsets (your Edit-mode view).
/// 3. Arrow keys / on-screen buttons to step through shots.
///
/// LIVE TUNING (per shot)
/// ──────────────────────
///   I / K      → pitch up / down
///   J / L      → yaw left / right
///   U / O      → FOV narrow / widen
///   W / S      → move forward / back  (along camera's look direction)
///   A / D      → move left / right
///   Q / E      → move up / down
///   Hold Shift → 5× faster on all keys
///   Z          → log current shot values to Console
///   R          → reset current shot to zero offsets + base position
/// </summary>
[RequireComponent(typeof(Camera))]
public class StoryboardCamera : MonoBehaviour
{
    // ── Shot definition ──────────────────────────────────────────────────────

    [System.Serializable]
    public class ShotData
    {
        public string id;
        [TextArea(1,2)] public string label;
        public float yawOffset;
        public float pitchOffset;
        public float fovOffset;
        [Tooltip("World-space position offset from the baseline camera position.")]
        public Vector3 posOffset;
    }

    [Header("Shots — generated by generate_shots.py from PLY geometry")]
    public List<ShotData> shotList = new List<ShotData>
    {
        new ShotData { id = "1A", label = "Campus Wide — Establishing",
                       pitchOffset = -1.9f,  yawOffset =   0f, fovOffset = +25f },
        new ShotData { id = "1B", label = "Courtyard — Tree as Center",
                       pitchOffset = -1.9f,  yawOffset =   0f, fovOffset =   0f },
        new ShotData { id = "1C", label = "Canopy — Looking Up",
                       pitchOffset = 0f, yawOffset = 0f, fovOffset = 0f,
                       posOffset = new Vector3(-0.056f, -0.400f, -1.239f) },
        new ShotData { id = "1D", label = "Roots — Looking Down",
                       pitchOffset = +126.40f, yawOffset = 0f, fovOffset = -10f },
        new ShotData { id = "1E", label = "Campus Right — Pan 90°",
                       pitchOffset = -1.9f,  yawOffset = +90f, fovOffset =   0f },
        new ShotData { id = "1F", label = "Campus Left — Pan 90°",
                       pitchOffset = -1.9f,  yawOffset = -90f, fovOffset =   0f },
    };

    [Header("Transition")]
    [Range(1f, 20f)] public float lerpSpeed = 6f;

    [Header("Tuning")]
    public float rotStep = 0.5f;   // degrees per frame (Shift = ×5)
    public float moveStep = 0.02f; // metres per frame  (Shift = ×5)

    // ── Internal state ───────────────────────────────────────────────────────

    Camera     _cam;
    int        _current = 1;

    Vector3    _basePos;
    Quaternion _baseRot;
    float      _baseFov;

    float   _curPitch, _curYaw, _curFov;
    Vector3 _curPos;

    // ── Unity lifecycle ───────────────────────────────────────────────────────

    void Awake()
    {
        _cam     = GetComponent<Camera>();
        _basePos = transform.position;
        _baseRot = transform.rotation;
        _baseFov = _cam.fieldOfView;

        Vector3 e = _baseRot.eulerAngles;
        _curPitch = e.x;
        _curYaw   = e.y;
        _curFov   = _baseFov;
        _curPos   = _basePos;

        SnapToShot(_current);
    }

    void Update()
    {
        bool shift = Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift);
        float rs = rotStep  * (shift ? 5f : 1f);
        float ms = moveStep * (shift ? 5f : 1f);

        // ── Shot navigation ──────────────────────────────────────────────────
        if (Input.GetKeyDown(KeyCode.RightArrow) || Input.GetKeyDown(KeyCode.DownArrow))
            GoToShot((_current + 1) % shotList.Count);
        if (Input.GetKeyDown(KeyCode.LeftArrow)  || Input.GetKeyDown(KeyCode.UpArrow))
            GoToShot((_current - 1 + shotList.Count) % shotList.Count);

        for (int i = 0; i < shotList.Count && i < 9; i++)
            if (Input.GetKeyDown(KeyCode.Alpha1 + i)) GoToShot(i);

        // ── Live tune — rotation & FOV ───────────────────────────────────────
        ShotData s = shotList[_current];

        if (Input.GetKey(KeyCode.I)) s.pitchOffset -= rs;
        if (Input.GetKey(KeyCode.K)) s.pitchOffset += rs;
        if (Input.GetKey(KeyCode.J)) s.yawOffset   -= rs;
        if (Input.GetKey(KeyCode.L)) s.yawOffset   += rs;
        if (Input.GetKey(KeyCode.U)) s.fovOffset   -= rs;
        if (Input.GetKey(KeyCode.O)) s.fovOffset   += rs;

        // ── Live tune — position (moves along camera's current axes) ─────────
        // Build a flat-yaw basis so W/S always moves horizontally toward the tree.
        Quaternion flatRot = Quaternion.Euler(0f, _curYaw, 0f);
        Vector3 fwd   =  flatRot * Vector3.forward;
        Vector3 right =  flatRot * Vector3.right;

        if (Input.GetKey(KeyCode.W)) s.posOffset += fwd   * ms;
        if (Input.GetKey(KeyCode.S)) s.posOffset -= fwd   * ms;
        if (Input.GetKey(KeyCode.A)) s.posOffset -= right * ms;
        if (Input.GetKey(KeyCode.D)) s.posOffset += right * ms;
        if (Input.GetKey(KeyCode.Q)) s.posOffset += Vector3.up   * ms;
        if (Input.GetKey(KeyCode.E)) s.posOffset -= Vector3.up   * ms;

        // ── Log / Reset ──────────────────────────────────────────────────────
        if (Input.GetKeyDown(KeyCode.Z)) LogCurrentShot();
        if (Input.GetKeyDown(KeyCode.R))
        {
            s.pitchOffset = 0; s.yawOffset = 0; s.fovOffset = 0;
            s.posOffset   = Vector3.zero;
        }

        // ── Smooth lerp to targets ───────────────────────────────────────────
        Vector3 be   = _baseRot.eulerAngles;
        float tPitch = be.x + s.pitchOffset;
        float tYaw   = be.y + s.yawOffset;
        float tFov   = _baseFov + s.fovOffset;
        Vector3 tPos = _basePos + s.posOffset;

        float t = Time.deltaTime * lerpSpeed;
        _curPitch = Mathf.LerpAngle(_curPitch, tPitch, t);
        _curYaw   = Mathf.LerpAngle(_curYaw,   tYaw,   t);
        _curFov   = Mathf.Lerp(_curFov, tFov, t);
        _curPos   = Vector3.Lerp(_curPos, tPos, t);

        transform.SetPositionAndRotation(_curPos, Quaternion.Euler(_curPitch, _curYaw, 0f));
        _cam.fieldOfView = _curFov;
    }

    // ── API ───────────────────────────────────────────────────────────────────

    public void GoToShot(int i)
    {
        _current = Mathf.Clamp(i, 0, shotList.Count - 1);
        Debug.Log($"[StoryboardCamera] → Shot {shotList[_current].id}");
    }

    void SnapToShot(int i)
    {
        _current  = i;
        ShotData s = shotList[i];
        Vector3 be = _baseRot.eulerAngles;
        _curPitch  = be.x + s.pitchOffset;
        _curYaw    = be.y + s.yawOffset;
        _curFov    = _baseFov + s.fovOffset;
        _curPos    = _basePos + s.posOffset;
        transform.SetPositionAndRotation(_curPos, Quaternion.Euler(_curPitch, _curYaw, 0f));
        _cam.fieldOfView = _curFov;
    }

    void LogCurrentShot()
    {
        ShotData s = shotList[_current];
        Debug.Log($"[StoryboardCamera] {s.id}" +
                  $"  pitch={s.pitchOffset:F2}  yaw={s.yawOffset:F2}  fov={s.fovOffset:F2}" +
                  $"  pos=({s.posOffset.x:F3},{s.posOffset.y:F3},{s.posOffset.z:F3})" +
                  $"  |  absRot({_curPitch:F1},{_curYaw:F1})  absPos({_curPos.x:F3},{_curPos.y:F3},{_curPos.z:F3})  fov{_curFov:F1}");
    }

    // ── HUD ──────────────────────────────────────────────────────────────────

    void OnGUI()
    {
        GUIStyle row = new GUIStyle(GUI.skin.label) { fontSize = 12 };
        GUIStyle btn = new GUIStyle(GUI.skin.button) { fontSize = 11 };

        ShotData cur = shotList[_current];

        GUI.Label(new Rect(8,  6, 800, 20), $"Shot {cur.id} — {cur.label}", row);
        GUI.Label(new Rect(8, 24, 800, 20),
            $"abs rot ({_curPitch:F1}, {_curYaw:F1})  fov {_curFov:F1}°  pos ({_curPos.x:F2},{_curPos.y:F2},{_curPos.z:F2})", row);
        GUI.Label(new Rect(8, 42, 800, 20),
            $"offsets  pitch{cur.pitchOffset:+0.0;-0.0;+0.0}  yaw{cur.yawOffset:+0.0;-0.0;+0.0}" +
            $"  fov{cur.fovOffset:+0.0;-0.0;+0.0}  pos({cur.posOffset.x:F2},{cur.posOffset.y:F2},{cur.posOffset.z:F2})", row);
        GUI.Label(new Rect(8, 60, 800, 20),
            "← →: shots  |  IK: pitch  JL: yaw  UO: FOV  WS: fwd/back  AD: strafe  QE: up/down  (Shift=fast)  Z: log  R: reset", row);

        if (GUI.Button(new Rect(8,  80, 50, 22), "◀", btn))
            GoToShot((_current - 1 + shotList.Count) % shotList.Count);
        if (GUI.Button(new Rect(62, 80, 50, 22), "▶", btn))
            GoToShot((_current + 1) % shotList.Count);

        float x = 120f;
        for (int i = 0; i < shotList.Count; i++)
        {
            Color prev = GUI.backgroundColor;
            GUI.backgroundColor = (i == _current) ? Color.yellow : Color.white;
            if (GUI.Button(new Rect(x, 80, 38, 22), shotList[i].id, btn)) GoToShot(i);
            GUI.backgroundColor = prev;
            x += 42f;
        }
    }
}
