import * as THREE from 'three';
import { SparkRenderer, SplatMesh } from '@sparkjsdev/spark';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

// ---------------------------------------------------------------------------
// World assets (generated by generate_viewer.py)
// ---------------------------------------------------------------------------
const SPZ_URL = 'https://cdn.marble.worldlabs.ai/5eb43da0-7bca-474f-bdea-2eb7f53d63e8/a9341a07-b8eb-4140-aa4e-e7e727dbe9d1_ceramic_500k.spz';

// ---------------------------------------------------------------------------
// Scene 01 shots — camera positions matching render_storyboard.py SHOTS
// yaw/pitch in degrees, fov in degrees, WHO/WHERE/WHEN from story_plot.py
// ---------------------------------------------------------------------------
const SHOTS = [
  {
    id: '1A', label: 'Full Campus — The Entire World Revealed',
    who: 'None', where: 'East campus, full establishing view', when: 'Early morning',
    yaw: 90, pitch: 0, fov: 100,
    characters: [],
  },
  {
    id: '1B', label: 'Courtyard Wide — Tree as Undeniable Center',
    who: 'The Tree', where: 'Central courtyard, ground level', when: 'Early morning',
    yaw: 0, pitch: 0, fov: 85,
    characters: [],
  },
  {
    id: '1C', label: "Worm's Eye — The Monolith Reveal",
    who: 'The Tree', where: 'Under the tree', when: 'Early morning',
    yaw: 0, pitch: 25, fov: 75,
    characters: [],
  },
  {
    id: '1D', label: 'Canopy Upshot — Natural Cathedral',
    who: 'The Tree', where: 'Under the tree', when: 'Mid-morning',
    yaw: 0, pitch: 45, fov: 80,
    characters: [],
  },
  {
    id: '1E', label: 'Root Level — Nature Reclaiming Stone',
    who: 'The Tree', where: 'Courtyard, ground level', when: 'Early morning',
    yaw: 0, pitch: -15, fov: 75,
    characters: [],
  },
  {
    id: '1F', label: 'Transition — Campus Full, Students Blind',
    who: 'Students (background)', where: 'Sports field, south campus', when: 'Mid-morning',
    yaw: 180, pitch: 0, fov: 95,
    characters: [
      { role: 'student', x: -2, z: -8, rotY: 0.3 },
      { role: 'student', x:  1, z: -6, rotY: -0.2 },
      { role: 'student', x:  3, z: -10, rotY: 0.5 },
    ],
  },
];

// ---------------------------------------------------------------------------
// Character placeholder colours (used until .fbx/glb files are provided)
// ---------------------------------------------------------------------------
const CHAR_COLORS = {
  zara:      0x8b7355,
  student:   0x4a6fa5,
  professor: 0x6b5b45,
};

// ---------------------------------------------------------------------------
// Three.js setup
// ---------------------------------------------------------------------------
const container = document.getElementById('canvas-container');
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
container.appendChild(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(85, window.innerWidth / window.innerHeight, 0.01, 1000);
camera.position.set(0, 1.6, 0);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.08;
controls.rotateSpeed = 0.4;
controls.zoomSpeed = 0.6;
controls.target.set(0, 1.6, -5);
controls.update();

// ---------------------------------------------------------------------------
// Spark renderer
// ---------------------------------------------------------------------------
const spark = new SparkRenderer({ renderer });

// ---------------------------------------------------------------------------
// Load the .spz world
// ---------------------------------------------------------------------------
const loadBar = document.getElementById('load-bar');
const loading = document.getElementById('loading');

const splat = new SplatMesh({ url: SPZ_URL });
splat.position.set(0, 0, 0);
scene.add(splat);

// Fake progress bar while splat loads
let progress = 0;
const fakeProgress = setInterval(() => {
  progress = Math.min(progress + Math.random() * 3, 90);
  loadBar.style.width = progress + '%';
}, 80);

splat.addEventListener('load', () => {
  clearInterval(fakeProgress);
  loadBar.style.width = '100%';
  setTimeout(() => {
    loading.style.opacity = '0';
    loading.style.transition = 'opacity 0.5s';
    setTimeout(() => loading.style.display = 'none', 500);
  }, 300);
  console.log('SPZ world loaded');
});

// ---------------------------------------------------------------------------
// Ambient + directional light (summer midday)
// ---------------------------------------------------------------------------
scene.add(new THREE.AmbientLight(0xfff8e8, 1.2));
const sun = new THREE.DirectionalLight(0xfff5d0, 2.5);
sun.position.set(2, 8, 3);
scene.add(sun);

// ---------------------------------------------------------------------------
// Character placeholders (capsule geometry, colored by role)
// Replaced by real .glb files when Mixamo assets are provided
// ---------------------------------------------------------------------------
const gltfLoader = new GLTFLoader();
const characterMeshes = {};

function makeCharacterPlaceholder(role) {
  const group = new THREE.Group();
  const color = CHAR_COLORS[role] || 0x888888;

  // Body
  const body = new THREE.Mesh(
    new THREE.CapsuleGeometry(0.22, 0.9, 4, 8),
    new THREE.MeshLambertMaterial({ color })
  );
  body.position.y = 0.85;
  group.add(body);

  // Head
  const head = new THREE.Mesh(
    new THREE.SphereGeometry(0.18, 8, 8),
    new THREE.MeshLambertMaterial({ color })
  );
  head.position.y = 1.65;
  group.add(head);

  // Phone (for students — small dark rectangle in front of face)
  if (role === 'student') {
    const phone = new THREE.Mesh(
      new THREE.BoxGeometry(0.07, 0.13, 0.01),
      new THREE.MeshLambertMaterial({ color: 0x111111, emissive: 0x223344, emissiveIntensity: 0.8 })
    );
    phone.position.set(0.12, 1.55, -0.22);
    group.add(phone);
  }

  return group;
}

function tryLoadGLB(role, path, onSuccess) {
  gltfLoader.load(
    path,
    (gltf) => { onSuccess(gltf.scene); },
    undefined,
    () => { onSuccess(makeCharacterPlaceholder(role)); }
  );
}

// Attempt to load real character files; fall back to placeholders
const charPaths = {
  zara:      '../characters/zara_idle.glb',
  student:   '../characters/student_texting_walk.glb',
  professor: '../characters/professor_idle.glb',
};

const charModels = {};
let loadedCount = 0;
const roles = Object.keys(charPaths);
roles.forEach(role => {
  tryLoadGLB(role, charPaths[role], (obj) => {
    charModels[role] = obj;
    loadedCount++;
  });
});

// ---------------------------------------------------------------------------
// Shot navigation
// ---------------------------------------------------------------------------
let currentShot = 0;

function buildNav() {
  const nav = document.getElementById('nav');
  const arrows = document.getElementById('arrows');
  nav.innerHTML = '';
  nav.appendChild(arrows);

  SHOTS.forEach((shot, i) => {
    const btn = document.createElement('button');
    btn.className = 'shot-btn' + (i === currentShot ? ' active' : '');
    btn.innerHTML = `<span class="shot-id">${shot.id}</span><span class="shot-name">${shot.label.split('—')[0].trim()}</span>`;
    btn.onclick = () => goToShot(i);
    nav.appendChild(btn);
  });

  arrows.querySelector('#btn-prev').onclick = () => goToShot((currentShot - 1 + SHOTS.length) % SHOTS.length);
  arrows.querySelector('#btn-next').onclick = () => goToShot((currentShot + 1) % SHOTS.length);
}

function goToShot(index) {
  currentShot = index;
  const shot = SHOTS[index];

  // Remove existing characters
  Object.values(characterMeshes).forEach(m => scene.remove(m));
  Object.keys(characterMeshes).forEach(k => delete characterMeshes[k]);

  // Place characters for this shot
  shot.characters.forEach((c, i) => {
    const model = charModels[c.role];
    if (!model) return;
    const clone = model.clone();
    clone.position.set(c.x, 0, c.z);
    clone.rotation.y = c.rotY || 0;
    clone.scale.setScalar(1.0);
    scene.add(clone);
    characterMeshes[`char_${i}`] = clone;
  });

  // Animate camera to shot position
  animateCamera(shot);

  // Update UI
  document.getElementById('shot-label').textContent = `Shot ${shot.id} — ${shot.label}`;
  updateCharInfo(shot);
  buildNav();
}

function updateCharInfo(shot) {
  const info = document.getElementById('char-info');
  if (shot.who === 'None') { info.style.display = 'none'; return; }
  info.style.display = 'block';
  document.getElementById('ci-who').textContent = `WHO: ${shot.who}`;
  document.getElementById('ci-where').textContent = `WHERE: ${shot.where}`;
  document.getElementById('ci-when').textContent = `WHEN: ${shot.when}`;
}

// ---------------------------------------------------------------------------
// Camera animation — convert yaw/pitch/fov to THREE.js look direction
// ---------------------------------------------------------------------------
function shotToLookTarget(shot) {
  const yawRad = THREE.MathUtils.degToRad(shot.yaw);
  const pitchRad = THREE.MathUtils.degToRad(shot.pitch);

  // Forward direction from yaw/pitch
  const dx = Math.sin(yawRad) * Math.cos(pitchRad);
  const dy = Math.sin(pitchRad);
  const dz = -Math.cos(yawRad) * Math.cos(pitchRad);

  return new THREE.Vector3(dx, 1.6 + dy * 5, dz * 5);
}

function animateCamera(shot) {
  camera.fov = shot.fov;
  camera.updateProjectionMatrix();

  const target = shotToLookTarget(shot);
  const startPos = camera.position.clone();
  const startTarget = controls.target.clone();
  const origin = new THREE.Vector3(0, 1.6, 0);

  let t = 0;
  const duration = 60; // frames

  function step() {
    t++;
    const alpha = 1 - Math.pow(1 - t / duration, 3); // ease out cubic
    camera.position.lerpVectors(startPos, origin, alpha);
    controls.target.lerpVectors(startTarget, target, alpha);
    controls.update();
    if (t < duration) requestAnimationFrame(step);
  }
  step();
}

// ---------------------------------------------------------------------------
// Keyboard navigation
// ---------------------------------------------------------------------------
window.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown')
    goToShot((currentShot + 1) % SHOTS.length);
  if (e.key === 'ArrowLeft' || e.key === 'ArrowUp')
    goToShot((currentShot - 1 + SHOTS.length) % SHOTS.length);
});

// ---------------------------------------------------------------------------
// Resize
// ---------------------------------------------------------------------------
window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

// ---------------------------------------------------------------------------
// Animation loop
// ---------------------------------------------------------------------------
function animate() {
  requestAnimationFrame(animate);
  controls.update();
  spark.render(scene, camera);
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------
buildNav();
goToShot(0);
animate();
